spring:
  application:
    name: es-trustSeal
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: 123456
    # 配置组件扫描路径，确保能扫描到公共模块中的异常处理器
  component-scan:
    base-packages: com.mc.escommon.exception, com.mc.estrustSeal.controller
# application.yml
  main:
    allow-circular-references: true

metrics:
  window-size: 300      # 5分钟时间窗口
  cleanup-interval: 60s # 内存清理间隔

springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /es-trustSeal/swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"
    configUrl: es-trustSeal/v3/api-docs/swagger-config
    urls:
      - name: es-trustSeal
        url: v3/api-docs

knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - gateway-service
  # 是否启用CORS跨域支持
  cors: true
server:
  port: 9086
# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:com.mc.estrustSeal.mapper/*.xml
  type-aliases-package: com.mc.estrustSeal.entity
config:
