spring:
  application:
    name: es-files
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /es-files/swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"
    configUrl: es-files/v3/api-docs/swagger-config
    urls:
      - name: es-files
        url: v3/api-docs

knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - gateway-service
  # 是否启用CORS跨域支持
  cors: true
server:
  port: 9083
