server:
  port: 9998

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: 123456
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - AddRequestHeader=origin,gateway
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: es-user-docs
          uri: http://localhost:9080
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - StripPrefix=1
        - id: es-mail-docs
          uri: http://localhost:9081
          predicates:
            - Path=/email/v3/api-docs
          filters:
            - StripPrefix=1
        - id: es-info-docs
          uri: http://localhost:9082
          predicates:
            - Path=/info/v3/api-docs
          filters:
            - StripPrefix=1
        - id: es-files-docs
          uri: http://localhost:9083
          predicates:
            - Path=/files/v3/api-docs
          filters:
            - StripPrefix=1
        - id: es-exam-docs
          uri: http://localhost:9084
          predicates:
            - Path=/exam/v3/api-docs
          filters:
            - StripPrefix=1
        - id: es-statistic-docs
          uri: http://localhost:9085
          predicates:
            - Path=/statistic/v3/api-docs
          filters:
            - StripPrefix=1
        - id: es-trustSeal-docs
          uri: http://localhost:9086
          predicates:
            - Path=/trustSeal/v3/api-docs
          filters:
            - StripPrefix=1
        - id: es-websocket-docs
          uri: http://localhost:9087
          predicates:
            - Path=/websocket/v3/api-docs
          filters:
            - StripPrefix=1
        - id: es-user
          uri: http://localhost:9080
          predicates:
            - Path=/user/**
        - id: es-user-markdown
          uri: http://localhost:9080
          predicates:
            - Path=/md/**
        - id: es-mail
          uri: http://localhost:9081
          predicates:
            - Path=/email/**
        - id: es-info
          uri: http://localhost:9082
          predicates:
            - Path=/info/**
        - id: es-files
          uri: http://localhost:9083
          predicates:
            - Path=/files/**
        - id: es-exam
          uri: http://localhost:9084
          predicates:
            - Path=/exam/**
        - id: es-statistic
          uri: http://localhost:9085
          predicates:
            - Path=/statistic/**
        - id: es-trustSeal
          uri: http://localhost:9086
          predicates:
            - Path=/trustSeal/**
        - id: es-websocket
          uri: http://localhost:9087
          predicates:
            - Path=/websocket/**

knife4j:
  gateway:
    enabled: true
    tags-sorter: order
    operations-sorter: order
    basic:
      enable: true
      username: 123456
      password: 123456
    strategy: manual
    routes:
      - name: 用户管理
        url: /user/v3/api-docs
        service-name: es-user
        context-path: /
        order: 1
      - name: 考试管理服务
        url: /exam/v3/api-docs
        service-name: es-exam
        context-path: /
        order: 2
      - name: 邮箱验证服务
        url: /email/v3/api-docs
        service-name: es-mail
        context-path: /
        order: 3
      - name: 系统信息服务
        url: /info/v3/api-docs
        service-name: es-info
        context-path: /
        order: 4
      - name: 文件服务
        url: /files/v3/api-docs
        service-name: es-files
        context-path: /
        order: 5
      - name: 统计服务
        url: /statistic/v3/api-docs
        service-name: es-statistic
        context-path: /
        order: 6
      - name: 认证服务
        url: /trustSeal/v3/api-docs
        service-name: es-trustSeal
        context-path: /
        order: 7
      - name: WebSocket 服务
        url: /websocket/v3/api-docs
        service-name: es-websocket
        context-path: /
        order: 8
    discover:
      enabled: false
  setting:
    language: zh-CN
    enable-footer: true
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright 2019-[浙江八一菜刀股份有限公司](https://gitee.com/xiaoym/knife4j)
  cors: true

config:
  redisTimeout: 60
